// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = 'https://placeholder.supabase.co';
const FALLBACK_SUPABASE_KEY = 'public-placeholder-key';
const TEMPLATE_SUPABASE_URL = 'https://your-project.supabase.co';
const TEMPLATE_SUPABASE_KEY = 'your-public-anon-key';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_KEY;
export const isSupabaseConfigured = ![
  FALLBACK_SUPABASE_URL,
  TEMPLATE_SUPABASE_URL,
].includes(SUPABASE_URL) && ![
  FALLBACK_SUPABASE_KEY,
  TEMPLATE_SUPABASE_KEY,
].includes(SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.warn('[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Using placeholder credentials.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});